In [26]:
# Імпортуємо необхідні бібліотеки
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [27]:
# Завантажуємо датасет
path_csv = "./IRIS.csv"
# Завантаження даних
data = pd.read_csv(path_csv)

In [28]:

# Розділяємо дані на ознаки та цільову змінну
X = data.drop('species', axis=1)
y = data['species']

In [29]:

# Розділяємо дані на тренувальний та тестовий набори
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [30]:
# Ініціалізуємо та навчаємо модель k-NN
k = 51  # Кількість найближчих сусідів
knn_model = KNeighborsClassifier(n_neighbors=k)
knn_model.fit(X_train, y_train)
print("k = ", k)

k =  51


In [31]:
# Прогнозуємо класи на тестовому наборі
y_pred = knn_model.predict(X_test)

In [32]:
# Оцінка точності моделі
accuracy = accuracy_score(y_test, y_pred)
print(f"Точність моделі: {accuracy:.2f}")

# Вивід звіту про класифікацію
print(classification_report(y_test, y_pred))

# Вивід матриці плутанини
conf_matrix = confusion_matrix(y_test, y_pred)
print("Матриця плутанини:")
print(conf_matrix)

Точність моделі: 0.97
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.90      1.00      0.95         9
 Iris-virginica       1.00      0.91      0.95        11

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30

Матриця плутанини:
[[10  0  0]
 [ 0  9  0]
 [ 0  1 10]]
